name = "DynamicQuantities"
uuid = "06fc5a27-2a28-4c7c-a15d-362465fb6821"
authors = ["MilesCranmer <miles.cranmer@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Ratios = "c84ed2f1-dad5-54f0-aa8e-dbefe2724439"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[weakdeps]
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[extensions]
DynamicQuantitiesUnitfulExt = "Unitful"

[compat]
Ratios = "0.4"
Requires = "1"
Unitful = "1"
julia = "1.6"

[extras]
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[targets]
test = ["Test", "SafeTestsets", "Unitful"]
